# version of docker-compose syntax
version: '3.7'

services:

  rabbit:
    image: rabbitmq:3.7-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .live.env
  
  db:
    image: postgres:13.2
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_prod_volume:/var/lib/postgresql/data/
    env_file:
      - .live.env

  app:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - static_data_prod_volume:/vol/web
    depends_on:
      - db
      - rabbit
    links:
      - rabbit
    env_file:
      - .live.env


  proxy:
    build:
      context: ./proxy_development
    volumes:
      - static_data_prod_volume:/vol/static
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  static_data_prod_volume:
  db_prod_volume: