# version of docker-compose syntax
version: '3.7'

services:

  rabbit:
    image: rabbitmq:3.7-management
    restart: always
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin
    env_file:
      - .debug.env
  
  db:
    image: postgres:12.5
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_dev_volume:/var/lib/postgresql/data/
    env_file:
      - .debug.env

  app:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - static_data_dev_volume:/vol/web
    depends_on:
      - db
      - rabbit
    expose:
      - "443"
    links:
      - rabbit
    env_file:
      - .debug.env


  proxy:
    build:
      context: ./proxy_development
    volumes:
      - static_data_dev_volume:/vol/static
    restart: always
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - app

volumes:
  static_data_dev_volume:
  db_dev_volume: