# Generated by Django 3.2 on 2021-05-07 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'ImageCategories',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='iidb')),
                ('description', models.CharField(help_text='tell us something in short that best describe your image(mandatory)', max_length=512)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('orb_descriptor', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField()),
                ('categories', models.ManyToManyField(blank=True, related_name='images', to='core.ImageCategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
